version: '3.8'
services:
 django:
      build:
       context: ./django/
       dockerfile: Dockerfile
      container_name: moviemanager_django_app
      volumes:
       - ./django/src/:/app/
      ports:
       - 8005:8005
      tty: true
      #command: "gunicorn -b 0.0.0.0:8005 --reload movie_app.wsgi:application"
      command: "python manage.py runserver 0.0.0.0:8005"
      depends_on:
        - postgres
 postgres:
    image: postgres:15.0
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg-data: