[tool.poetry]
name = "MovieManager App"
version = "0.1.0"
description = ""
authors = ["Thomas SOUTIF"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.3"
gunicorn = "^20.1.0"
python-dotenv = "^0.21.0"
psycopg2-binary = "^2.9.5"
djangorestframework = "^3.14.0"
